BEGIN;

CREATE TABLE IF NOT EXISTS public.usuario_sede (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint NOT NULL REFERENCES public.usuario(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  sede_id bigint NOT NULL REFERENCES public.sede(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_usuario_sede_usuario_id ON public.usuario_sede(usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_sede_sede_id ON public.usuario_sede(sede_id);
CREATE INDEX IF NOT EXISTS idx_usuario_sede_activo ON public.usuario_sede(activo);
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuario_sede_activa
  ON public.usuario_sede(usuario_id, sede_id) WHERE activo = true;

CREATE OR REPLACE FUNCTION public.fn_validar_usuario_sede_empresa()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE rol_usuario text; empresa_nueva bigint; empresa_existente bigint;
BEGIN
  IF NEW.activo = false THEN RETURN NEW; END IF;
  SELECT rol INTO rol_usuario FROM public.usuario WHERE id = NEW.usuario_id FOR UPDATE;
  IF rol_usuario IS DISTINCT FROM 'admin_empresa' THEN
    RAISE EXCEPTION 'usuario_sede solo admite usuarios admin_empresa';
  END IF;
  SELECT empresa_id INTO empresa_nueva FROM public.sede WHERE id = NEW.sede_id;
  SELECT s.empresa_id INTO empresa_existente
    FROM public.usuario_sede us JOIN public.sede s ON s.id = us.sede_id
   WHERE us.usuario_id = NEW.usuario_id AND us.activo = true
     AND (TG_OP = 'INSERT' OR us.id <> NEW.id) LIMIT 1;
  IF empresa_existente IS NOT NULL AND empresa_existente <> empresa_nueva THEN
    RAISE EXCEPTION 'todas las sedes del administrador deben pertenecer a la misma empresa';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_validar_usuario_sede_empresa ON public.usuario_sede;
CREATE TRIGGER trg_validar_usuario_sede_empresa
BEFORE INSERT OR UPDATE ON public.usuario_sede
FOR EACH ROW EXECUTE FUNCTION public.fn_validar_usuario_sede_empresa();

COMMIT;
