-- Recuperación de contraseña: bandera de cambio forzado + tokens de restablecimiento.
-- Idempotente: puede ejecutarse varias veces sin efectos secundarios.
BEGIN;

-- Marca que el usuario debe cambiar su contraseña en el próximo inicio de sesión
-- (p. ej. tras un reseteo del superior a la contraseña temporal).
ALTER TABLE public.usuario
  ADD COLUMN IF NOT EXISTS requiere_cambio_contrasena boolean NOT NULL DEFAULT false;

-- Tokens de un solo uso y de vida corta para restablecer la contraseña.
--  tipo = 'propio'    -> el propio usuario restablece su clave desde el enlace recibido por correo.
--  tipo = 'superior'  -> un superior directo confirma el reseteo a la contraseña temporal.
CREATE TABLE IF NOT EXISTS public.usuario_restablecimiento_contrasena (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint NOT NULL REFERENCES public.usuario(id) ON UPDATE CASCADE ON DELETE CASCADE,
  tipo text NOT NULL CHECK (tipo IN ('propio', 'superior')),
  hash_token text NOT NULL,
  superior_id bigint REFERENCES public.usuario(id) ON UPDATE CASCADE ON DELETE SET NULL,
  expira_en timestamptz NOT NULL,
  usado_en timestamptz,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_usuario_restablecimiento_hash_token
  ON public.usuario_restablecimiento_contrasena(hash_token);
CREATE INDEX IF NOT EXISTS idx_usuario_restablecimiento_usuario_id
  ON public.usuario_restablecimiento_contrasena(usuario_id);

COMMIT;
