/**
 * @file api-error-code.ts
 * @description Códigos de error estables expuestos por la API en respuestas de fallo.
 */

/** Mapa de códigos de error de negocio y técnicos soportados por la API. */
export const API_ERROR_CODE = {
  UNKNOWN: "UNKNOWN_ERROR",
  VALIDATION: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",

  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_SSO_HEADER_MISSING: "AUTH_SSO_HEADER_MISSING",

  GLPI_UNAVAILABLE: "GLPI_UNAVAILABLE",
  GLPI_AUTH_FAILED: "GLPI_AUTH_FAILED",
  GLPI_SESSION_EXPIRED: "GLPI_SESSION_EXPIRED",
  GLPI_RESOURCE_NOT_FOUND: "GLPI_RESOURCE_NOT_FOUND",
  GLPI_BAD_REQUEST: "GLPI_BAD_REQUEST",
  GLPI_FORBIDDEN: "GLPI_FORBIDDEN",

  INVALID_CATEGORY: "INVALID_CATEGORY",
  INVALID_LOCATION: "INVALID_LOCATION",
  INVALID_TECHNICIAN: "INVALID_TECHNICIAN",
  INVALID_TICKET_TYPE: "INVALID_TICKET_TYPE",
  INVALID_TICKET_STATUS: "INVALID_TICKET_STATUS",

  ATTACHMENT_TYPE_NOT_ALLOWED: "ATTACHMENT_TYPE_NOT_ALLOWED",
  ATTACHMENT_TOO_LARGE: "ATTACHMENT_TOO_LARGE",
  ATTACHMENT_UPLOAD_FAILED: "ATTACHMENT_UPLOAD_FAILED",

  MAIL_SEND_FAILED: "MAIL_SEND_FAILED",
} as const;

/** Unión de todos los códigos definidos en {@link API_ERROR_CODE}. */
export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
